In [ ]:
# Classifying movie reviews: Binary classification using the IMDb dataset.

In [ ]:
# for binary classification
# logistic regression
# KNN(exam)
# decision tree
# SVM
# Naive Bayes


IMDB dataset

KNN(for exam)

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
#load
(x_train, y_train), (x_test, y_test)=imdb.load_data(num_words=10000)

In [ ]:
#preprocess
X_train=pad_sequences(x_train, maxlen=200)
X_test=pad_sequences(x_test, maxlen=200)

In [ ]:
from sklearn.feature_extraction.text import TfidfTransformer
tfid_fTransformer= TfidfTransformer()
X_train_tfidf=tfid_fTransformer.fit_transform(X_train)
X_test_tfidf=tfid_fTransformer.fit_transform(X_test)

In [ ]:
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_tfidf, y_train)

KNeighborsClassifier()

In [ ]:
y_pred=knn.predict(X_test_tfidf)

In [ ]:
accuracy= accuracy_score(y_test,y_pred)
print("Accuracy: ",accuracy)

Accuracy:  0.50696


In [ ]:
print("Confusion matrix:")
conf=confusion_matrix(y_test,y_pred)
print(conf)

Confusion matrix:
[[6407 6093]
 [6233 6267]]


In [ ]:
print("Classification report:")
print(classification_report(y_test,y_pred))

Classification report:
              precision    recall  f1-score   support

           0       0.51      0.51      0.51     12500
           1       0.51      0.50      0.50     12500

    accuracy                           0.51     25000
   macro avg       0.51      0.51      0.51     25000
weighted avg       0.51      0.51      0.51     25000



Logistic Regression

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
#load
(x_train, y_train), (x_test, y_test)=imdb.load_data(num_words=10000)

In [ ]:
#preprocess
X_train=pad_sequences(x_train, maxlen=200)
X_test=pad_sequences(x_test, maxlen=200)

In [ ]:
from sklearn.feature_extraction.text import TfidfTransformer
tfid_fTransformer= TfidfTransformer()
X_train_tfidf=tfid_fTransformer.fit_transform(X_train)
X_test_tfidf=tfid_fTransformer.fit_transform(X_test)

In [ ]:
model=LogisticRegression()
model.fit(X_train_tfidf, y_train)

LogisticRegression()

In [ ]:
y_pred=model.predict(X_test_tfidf)

In [ ]:
accuracy= accuracy_score(y_test,y_pred)
print("Accuracy: ",accuracy)

print("Confusion matrix:")
print(confusion_matrix(y_test,y_pred))

Accuracy:  0.51052
Confusion matrix:
[[6464 6036]
 [6201 6299]]


In [ ]:
print("Classification report:")
print(classification_report(y_test,y_pred))

Classification report:
              precision    recall  f1-score   support

           0       0.51      0.52      0.51     12500
           1       0.51      0.50      0.51     12500

    accuracy                           0.51     25000
   macro avg       0.51      0.51      0.51     25000
weighted avg       0.51      0.51      0.51     25000



Decision tree

In [ ]:
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
#load
(x_train, y_train), (x_test, y_test)=imdb.load_data(num_words=10000)
#preprocess
X_train=pad_sequences(x_train, maxlen=200)
X_test=pad_sequences(x_test, maxlen=200)

In [ ]:
from sklearn.feature_extraction.text import TfidfTransformer
tfid_fTransformer= TfidfTransformer()
X_train_tfidf=tfid_fTransformer.fit_transform(X_train)
X_test_tfidf=tfid_fTransformer.fit_transform(X_test)

In [ ]:
model=DecisionTreeClassifier()
model.fit(X_train_tfidf, y_train)

DecisionTreeClassifier()

In [ ]:
y_pred=model.predict(X_test_tfidf)

In [ ]:
accuracy= accuracy_score(y_test,y_pred)
print("Accuracy: ",accuracy)

print("Confusion matrix:")
print(confusion_matrix(y_test,y_pred))


Accuracy:  0.50752
Confusion matrix:
[[6468 6032]
 [6280 6220]]


In [ ]:
print("Classification report:")
print(classification_report(y_test,y_pred))

Classification report:
              precision    recall  f1-score   support

           0       0.51      0.52      0.51     12500
           1       0.51      0.50      0.50     12500

    accuracy                           0.51     25000
   macro avg       0.51      0.51      0.51     25000
weighted avg       0.51      0.51      0.51     25000



In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load dataset
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=10000)

# Convert integer sequences back to words
word_index = imdb.get_word_index()
reverse_word_index = {value: key for key, value in word_index.items()}
x_train = [' '.join([reverse_word_index.get(i - 3, '?') for i in seq]) for seq in x_train]
x_test = [' '.join([reverse_word_index.get(i - 3, '?') for i in seq]) for seq in x_test]

# Split the training data for validation
x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.2, random_state=42)

# TF-IDF vectorization
tfidf_vectorizer = TfidfVectorizer(max_features=10000)
X_train_tfidf = tfidf_vectorizer.fit_transform(x_train)
X_val_tfidf = tfidf_vectorizer.transform(x_val)
X_test_tfidf = tfidf_vectorizer.transform(x_test)

# KNN classifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_tfidf, y_train)

# Predictions
y_val_pred = knn.predict(X_val_tfidf)
y_test_pred = knn.predict(X_test_tfidf)

# Evaluate model
print("Validation Accuracy:", accuracy_score(y_val, y_val_pred))
print("Test Accuracy:", accuracy_score(y_test, y_test_pred))
print("Classification Report:\n", classification_report(y_test, y_test_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_test_pred))


1641221/1641221 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
Validation Accuracy: 0.7522
Test Accuracy: 0.67208
Classification Report:
               precision    recall  f1-score   support

           0       0.65      0.74      0.69     12500
           1       0.70      0.60      0.65     12500

    accuracy                           0.67     25000
   macro avg       0.68      0.67      0.67     25000
weighted avg       0.68      0.67      0.67     25000

Confusion Matrix:
 [[9256 3244]
 [4954 7546]]


In [ ]:
from sklearn.model_selection import GridSearchCV

# Define parameter grid
param_grid = {
    'n_neighbors': [3, 5, 7, 9],
    'weights': ['uniform', 'distance']
}

# Grid search
grid_search = GridSearchCV(KNeighborsClassifier(), param_grid, cv=5)
grid_search.fit(X_train_tfidf, y_train)

# Best parameters
print("Best Parameters:", grid_search.best_params_)

# Evaluate the best model
best_knn = grid_search.best_estimator_
y_val_pred = best_knn.predict(X_val_tfidf)
y_test_pred = best_knn.predict(X_test_tfidf)

print("Validation Accuracy:", accuracy_score(y_val, y_val_pred))
print("Test Accuracy:", accuracy_score(y_test, y_test_pred))
print("Classification Report:\n", classification_report(y_test, y_test_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_test_pred))


Best Parameters: {'n_neighbors': 9, 'weights': 'distance'}
Validation Accuracy: 0.7648
Test Accuracy: 0.6926
Classification Report:
               precision    recall  f1-score   support

           0       0.67      0.76      0.71     12500
           1       0.72      0.62      0.67     12500

    accuracy                           0.69     25000
   macro avg       0.70      0.69      0.69     25000
weighted avg       0.70      0.69      0.69     25000

Confusion Matrix:
 [[9535 2965]
 [4720 7780]]
